project 'VideoRecording.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoRecording' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSS3'
  pod 'AWSMobileClient'
  pod 'AssetsPickerViewController', '~> 2.0'
  # Pods for VideoRecording

end
